[build]
  command = "npm run build --prefix admin"
  publish = "admin/dist"

[dev]
  command = "npm run dev --prefix admin"
  port = 8888

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
